### ISSUE TITLE
AVIF images not working

### ISSUE THREAD

**Issue by LITUATUI** [colinwilson/lotusdocs#100]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

If I use AVIF images, I get this error:

`Error: error building site: "/home/pedro/Documentos/GitHub/m3upt-lotusdocs/content/docs/intro.md:1:1": "/home/pedro/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/colinwilson/lotusdocs@v0.1.0/layouts/docs/_markup/render-image.html:18:77": execute of template failed: template: docs/_markup/render-image.html:18:77: executing "docs/_markup/render-image.html" at <.Width>: error calling Width: this method is only available for image resources
`

### Expected behavior

It works fine if I use the JPG format.

### Environment

```markdown
- OS: I use Arch btw
- Browser: Chromium
- Browser Version: latest
```

**Comment by colinwilson** [comment]
Hugo's [image processing](https://gohugo.io/content-management/image-processing/) doesn't support the AVIF image format currently :( - [see here](https://github.com/gohugoio/hugo/issues/7837#issuecomment-1063793230)

**Comment by LITUATUI** [comment]
Yes, I know that Hugo can't process AVIF images.

However I use AVIF images with other Hugo themes without problems. The theme just has to not process the image.

Some themes like [Clarity](https://github.com/chipzoller/hugo-clarity#support-for-modern-image-formats) or [Hugo Bootstrap](https://github.com/razonyang/hugo-theme-bootstrap/pull/490) even have a neat feature to display AVIF images with fallback formats (in case the browser doesn't support it).

**Comment by colinwilson** [comment]
Ah, I see.

That's more of a feature request then. I'll close this. Make a feature request in the discussion section, I track (and implement) feature requests there.
