### ISSUE TITLE
No copy codeblock for non-prism highlighting

### ISSUE THREAD

**Issue by qjcg** [colinwilson/lotusdocs#105]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

With `params.docs.prism = false` set in `hugo.toml`, no copy codeblock button is present on code blocks.

### Expected behavior

A copy codeblock button is present on code blocks when `prism = false`.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by colinwilson** [comment]
Yep.

With `params.docs.prism = false` the theme reverts to Hugo's default syntax highlighter [Chroma](https://github.com/alecthomas/chroma), which doesn't feature a copy button.

However, there is a way to implement this. Make a feature request in the discussions section of the repo. I track all feature request there.

**Comment by qjcg** [comment]
Thanks for the quick reply, copy that and will do!

**Comment by qjcg** [comment]
Created the feature request here:

https://github.com/colinwilson/lotusdocs/discussions/106

**Comment by colinwilson** [comment]
> Created the feature request here:

Excellent. Thanks 👍
