### ISSUE TITLE
How can i edit the landing page?

### ISSUE THREAD

**Issue by HilkopterBob** [colinwilson/lotusdocs#116]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

How can i edit the landing page? 

### Expected behavior

i guess it should be possible to edit it, and it should be documented to

### Environment

```markdown
- OS: Debian 12.2
- Browser: Edge
- Browser Version: 116
```

**Comment by elizabethyalkut** [comment]
You'll have to create a `landing.yaml` file in `data` to override the defaults, and you can use the one in exampleSite to see how it works.

**Comment by artberger** [comment]
I was trying out the landing page feature and opened a follow-on issue with some problems I was having: https://github.com/colinwilson/lotusdocs/issues/128. I think it's different than this issue, but just thought I'd comment to show some ways I had tried to edit the landing page.
