### ISSUE TITLE
在iPhone上显示有问题

### ISSUE THREAD

**Issue by cba023** [colinwilson/lotusdocs#12]
在iPhone上显示有问题， "返回顶部"按钮异常

**Comment by colinwilson** [comment]
> There is a problem with the display on the iPhone, and the "back to top" button is abnormal

Thank you. 

I see the issue with the back-to-top button, but can you provide more info regarding the display issue(s)? What version of iOS are you using?

**Comment by cba023** [comment]
iPhone 12， 系统是最新版，运行在Safari上， 语言环境 中文，截图我没有了，“回到顶部”按钮好像变成了矩形，中间的箭头的位置有一点点异常

**Comment by colinwilson** [comment]
> iPhone 12, the system is the latest version, running on Safari, the locale is Chinese, I don’t have the screenshot, the “Back to Top” button seems to have become a rectangle, and the position of the arrow in the middle is a little bit abnormal

Thank you. I'll fix this soon.

**Comment by colinwilson** [comment]
Fixed by 3b9d14a

**Comment by cba023** [comment]
👍👍

发自我的 iPhone

在 2023年8月15日，02:25，Colin Wilson ***@***.***> 写道：

﻿

Closed #12<https://github.com/colinwilson/lotusdocs/issues/12> as completed.
