### ISSUE TITLE
Scrolling in FlexSearch

### ISSUE THREAD

**Issue by ghost** [colinwilson/lotusdocs#13]
Hello,

 loving the theme! 
 
 However, FlexSearch results are not scroll-able and they very often overflow outside the screen. Is there a way to add a maximum height to the suggestions container with scrolling?
 
 Thanks for the help!

**Comment by colinwilson** [comment]
Thank you. Glad you like the theme 🙏

> FlexSearch results are not scroll-able and they very often overflow outside the screen

Thanks for pointing this out. I'll push an update to resolve this soon.

Did you experience this on a Desktop or Mobile view?

**Comment by ghost** [comment]
Thanks for the quick response!

I'm experiencing this on all views, with multiple browsers. Temporarily, to get around it, I added:
`style="height: 500px; overflow-y: auto"`
To the `suggestions` container in `top-header.html`. I think there must be a cleaner way to do it through flexsearch.html, but I'm still learning my way around hugo themes.

**Comment by colinwilson** [comment]
This is helpful, thank you.

I'm inclined to implement your workaround via the `_flexsearch.scss` file.

**Comment by colinwilson** [comment]
Fixed by f126cd8
