### ISSUE TITLE
Unable to Build from Quickstart Page (March 1st, 2024)

### ISSUE THREAD

**Issue by vincentmaule** [colinwilson/lotusdocs#161]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

Complete Newbie to Hugo so this may be a mistake on my part.

Followed the instructions from the [Quickstart](https://lotusdocs.dev/docs/quickstart/) Guide.

High Level Overview:

1. Installed Hugo & Go.
  a. go version = go1.22.0 linux/amd64
  b. hugo version = hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
2. Use Hugo to make a new site & cd into said directory.
3. Initialized project (site) as a Module as a Git Rep.
  a. module git.repo.........................................................
    go 1.22.0
    require (
      github.com/colinwilson/lotusdocs v0.1.0 // indirect
      github.com/gohugoio/hugo-mod-bootstrap-scss/v5 v5.20300.20200 // indirect
    )
4. Add Lotus Docs as a Module to Project (site).
5. Create new Content (Example Page). *Note: Please let me know if I should not be sharing the full text of the below; AKA, Cipher text.*
     github.com/colinwilson/lotusdocs v0.1.0 h1:oTC8pAYQp9XDNaUwE4SEY+id3ByNELxIIFrktYEGxYA=
      github.com/colinwilson/lotusdocs v0.1.0/go.mod h1:9zu2REJDi+zdPRcR5/bRYSUR7gkNF4NQLvV38SEoCP8=
      github.com/gohugoio/hugo-mod-bootstrap-scss/v5 v5.20300.20200             h1:SmpwwN3DNzJWbV+IT8gaFu07ENUFpCvKou5BHYUKuVs=
      github.com/gohugoio/hugo-mod-bootstrap-scss/v5 v5.20300.20200/go.mod h1:kx8MBj9T7SFR8ZClWvKZPmmUxBaltkoXvnWlZZcSnYA=
      github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2 v2.21100.20000/go.mod h1:mFberT6ZtcchrsDtfvJM7aAH2bDKLdOnruUHl0hlapI=
      github.com/twbs/bootstrap v5.3.2+incompatible/go.mod h1:fZTSrkpSf0/HkL0IIJzvVspTt1r9zuf7XlZau8kpcY0=
6. Pushed code to git repo.
7. Attempt to run this command: hugo server -D
```
user@machine:~/Documents/sites/site$ hugo server -D
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
ERROR 2024/03/01 22:34:21 render of "page" failed: execute of template failed: template: docs/single.html:25:44: executing "docs/single.html" at <partial (printf "%s/%s" ($.Scratch.Get "pathName") "breadcrumbs.html") .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/colinwilson/lotusdocs@v0.1.0/layouts/partials/docs/breadcrumbs.html:5:55": execute of template failed: template: partials/docs/breadcrumbs.html:5:55: executing "partials/docs/breadcrumbs.html" at <.Ancestors.Reverse>: can't evaluate field Ancestors in type *hugolib.pageState
Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: docs/list.html:25:44: executing "docs/list.html" at <partial (printf "%s/%s" ($.Scratch.Get "pathName") "breadcrumbs.html") .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/colinwilson/lotusdocs@v0.1.0/layouts/partials/docs/breadcrumbs.html:5:55": execute of template failed: template: partials/docs/breadcrumbs.html:5:55: executing "partials/docs/breadcrumbs.html" at <.Ancestors.Reverse>: can't evaluate field Ancestors in type *hugolib.pageState
Built in 709 ms
```

### Expected behavior

As referenced in this [page](https://lotusdocs.dev/docs/quickstart/#preview-your-site), a generated page.

### Environment

```markdown
- OS: PopOS
- Browser: N/A
- Browser Version: N/A
```

**Comment by noxilixon** [comment]
Your hugo version is too old. You use `hugo v0.92.2+extended `. But in the [Readme](https://github.com/colinwilson/lotusdocs) it says that you need `Hugo Extended (minimum version: 0.120.0)`. If this version is not available in your OS repository you can use the [binary release](https://gohugo.io/installation/linux/#prebuilt-binaries).

**Comment by vincentmaule** [comment]
Thanks for sharing something that I overlooked, will close issue based on feedback.
