### ISSUE TITLE
Code Highlighting Doesn't Work Properly on Desktop Browsers

### ISSUE THREAD

**Issue by ghost** [colinwilson/lotusdocs#29]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

Code blocks containing highlighted lines don't render on desktop browsers. I've tested this with Firefox and Chrome (without addons and also in private mode).

Additionally, if a wide code block is viewed on a smaller screen, horizontal scrollbar appears between the code text and code margin.

It works properly in mobile browsers.

Example [this link](https://katalog.ci/docs/concepts/embedded-types/) renders differently on desktop and mobile.

The website is deployed on an NGINX server. Except for the automatic LetsEncrypt setup, the config file is at a bare minimum (happy to share if needed). 

### Expected behavior

+ Code blocks to be highlighted on desktop browsers.

+ Horizontal lines to appear at the margin instead of above it. 

### Screenshots

Desktop browsers will smaller screen:

<img width="946" alt="horizontal_scrollbar_2" src="https://github.com/colinwilson/lotusdocs/assets/52619598/f78a6c33-0ec2-4180-98bd-bffe9eb83016">

Desktop browsers will smaller screen:

<img width="947" alt="horizontal_scrollbar_1" src="https://github.com/colinwilson/lotusdocs/assets/52619598/dfa9f995-aef3-47fd-8df0-d9dad44f3631">

Common to all desktop browsers

<img width="946" alt="code_not_highlighted" src="https://github.com/colinwilson/lotusdocs/assets/52619598/10de53e7-dde9-4e91-b5a6-6cb12980cdf9">

**Comment by colinwilson** [comment]
I think this is your NGINX config. Checking Chrome/Firefox dev tools shows many [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) warnings for the `.js` files needed for highlighting to function. NGINX is trying to load them over `http://`

**Comment by colinwilson** [comment]
I think that's also what's causing your code blocks to render incorrectly

**Comment by ghost** [comment]
Thanks @colinwilson ! 
I've updated the NGINX config to allow only HTTPS and things are working consistently across devices.
