### ISSUE TITLE
Publish as Gitlab Pages

### ISSUE THREAD

**Issue by MaKaNu** [colinwilson/lotusdocs#30]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

I have a working instance of gitlab with working gitlab-pages. The Plain-HTML Pages is working the hugo template from gitlab isn't working and the Gitlab Hugo Pages Example works but looks weird. But my locally build which works fine locally with lotusdocs completes the CI/CD. I am using `GO v1.21.0` but it seems that the latest Hugo-extended uses `GO v1.23.0`. My Pipeline was running after I switched to `hugo-extended:0.109.0`. 

My Hugo Config is so far the basic one and it works fine locally. The only issue seems that the copying to public or something else isn't working as expected. This is the output of the build and it seems that something is missing:

```bash
$ hugo mod get -u $THEME_URL
go: downloading github.com/colinwilson/lotusdocs v0.0.0-20230824022610-a7d660221d18
$ hugo
Start building sites … 
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended linux/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
WARN 2023/08/24 12:11:51 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/08/24 12:11:51 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/08/24 12:11:51 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/08/24 12:11:51 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/08/24 12:11:51 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/08/24 12:11:51 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
                   | EN  
-------------------+-----
  Pages            |  5  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  
Total in 15 ms
```
Sadly I have to little insight to grasp what might cause the issue.

The following is the gitlab CICD:

```bash
image: registry.gitlab.com/pages/hugo/hugo_extended:0.109.0

variables:
  HUGO_ENV: production
  THEME_URL: "github.com/colinwilson/lotusdocs"

default:
  tags:
    - docker
    - linux
  before_script:
    - apk add --no-cache go curl bash nodejs
    - hugo mod get -u $THEME_URL
    ## Uncomment the following if you use PostCSS. See https://gohugo.io/hugo-pipes/postcss/
    #- npm install postcss postcss-cli autoprefixer

test:
  tags:
    - docker
    - linux
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  tags:
    - docker
    - linux
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
```
So at the end I only get 404s.

### Expected behavior

With successfull build and deploy I expect a working Pages Site

### Environment

```markdown
- OS: Arch Linux
- Browser: Firefox
- Browser Version: 116
```

**Comment by saurabh-mish** [comment]
@MaKaNu - I think this line is causing the issue

```
- hugo mod get -u $THEME_URL
```

I would make the recommended changes based on [these instructions](https://lotusdocs.dev/docs/quickstart/). I think its very convenient to import the theme as a module in `hugo.toml`.

If you do it this way, you won't need to do `- hugo mod get -u $THEME_URL` - the `hugo` command in the `test` and `pages` stages *could* be enough.

**Comment by colinwilson** [comment]
I don't think you need the `THEME_URL` environment variable and `hugo mod get -u $THEME_URL` command in the `before_script:` block. As long as the `hugo.toml` and `go.mod` files in your repo are configured with the theme module info.

<details>
  <summary>hugo.toml</summary>

  ```toml
baseURL = 'https://colinwilson.gitlab.io'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10
```
</details>

<details>
  <summary>go.mod</summary>

  ```go
module pages

go 1.20

require (
	github.com/colinwilson/lotusdocs v0.0.0-20230824022610-a7d660221d18 // indirect
	github.com/gohugoio/hugo-mod-bootstrap-scss/v5 v5.20300.20003 // indirect
)
```
</details>

Try the following config which uses the latest Hugo version:
```
image: registry.gitlab.com/pages/hugo/hugo_extended:0.117.0

variables:
  HUGO_ENV: production
  # THEME_URL: "github.com/colinwilson/lotusdocs"

default:
  tags:
    - docker
    - linux
  before_script:
    - apk add --no-cache go curl bash nodejs
    # - hugo mod get -u $THEME_URL
    ## Uncomment the following if you use PostCSS. See https://gohugo.io/hugo-pipes/postcss/
    #- npm install postcss postcss-cli autoprefixer

test:
  tags:
    - docker
    - linux
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  tags:
    - docker
    - linux
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
```

My test using the above config: [colinwilson.gitlab.io](https://colinwilson.gitlab.io)

**Comment by MaKaNu** [comment]
Are you really able to build with version 117?

If I have selected 0.117.0 and my go.mod states 1.20 or 1.21 I will get

```bash
$ hugo
go: errors parsing go.mod:
/builds/testumgebung/pages-test/go.mod:3: invalid go version '1.20.0': must match format 1.23
```

I changed the Version in `go.mod` to 1.23 and used 0.117.0 and now the Output looks similar to what I see if I run it locally. But something else seems weird I builded also locally and got for pages and local a similar result while running local with `hugo server` looks fine:
![image](https://github.com/colinwilson/lotusdocs/assets/32844273/4e6488ea-bce2-459c-ac67-b851209b0e2d)

**Comment by ghost** [comment]
The [quickStart](https://lotusdocs.dev/docs/quickstart/#create-a-new-lotus-docs-site) guide is accurate. If you follow the guide and try to run it locally, you should be able to do it in GitLab's CI. 

I followed the guide and imported this theme as a module. For deployments I generate static webpages using:

```
hugo --buildDrafts --ignoreCache --cleanDestinationDir
```

and haven't run into any issues.

**Comment by MaKaNu** [comment]
I followed the quickstart guide and https://lotusdocs.dev/docs/quickstart/#preview-your-site works well. I tried your flags for deployment, but still got my issues. I restart next week with a new fresh repo and will see if it behave different.

**Comment by colinwilson** [comment]
@MaKaNu 

> `invalid go version '1.20.0': must match format 1.23`

Is the Go version in your `go.mod` file written as `1.20.0`? If so change it to `1.20` (See if that helps)

**Comment by colinwilson** [comment]
@MaKaNu

P.S. Here's my repo on GitLab [https://gitlab.com/colinwilson/colinwilson.gitlab.io](https://gitlab.com/colinwilson/colinwilson.gitlab.io).

Hope it helps 👍
