### ISSUE TITLE
Sidebar nav does not correctly display nested dropdowns

### ISSUE THREAD

**Issue by Nadine2016** [colinwilson/lotusdocs#35]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

When having nested dropdowns in the left-hand sidebar, the second dropdown displays as a single page as shown in the following image. 

<img width="310" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/3b3043b9-14e4-4b62-8d27-8fd1aeeeeb07">

Even though Dropdown 2 has topics underneath, these will not be displayed in the nav. But once you click on Dropdown 2, the subtopics will display in the middle panel. 

<img width="723" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/3a52a6ec-22ff-472b-b4f9-7524ce8eb629">

This is my local folder structure

<img width="243" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/f7e42ac1-0bd5-408a-b0fc-2c8bde8ab397">

### Expected behavior

Properly display nested dropdowns in the left-hand sidebar. 

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 116
```

**Comment by colinwilson** [comment]
I'll look at this.

I think I configured a setting somewhere to determine how many nested menu levels the sidebar supports (default 2).
