### ISSUE TITLE
Alerts are not indented when used in lists

### ISSUE THREAD

**Issue by Nadine2016** [colinwilson/lotusdocs#59]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

When using the alert shortcode within an ordered list, the alert is not getting indented, but instead gets left aligned. Because of that, the numbering within the ordered list is off. 

Example code: 

-------

1. This is a test command. 
   ```yaml
   kubectl apply -f- <<EOF
   apiversion: v1
   test: value 
   EOF 
   ```

2. This is the second command. 
   ```sh
   kubectl get pods 
   ```

   {{% alert icon="🍅" context="success" %}} 
   This is an alert that should be indented. 
   {{% /alert %}}

3. Test
   {{% alert icon="🍅" context="success" %}} 
   Another alert. 
   {{% /alert %}}

------

It will display as follows: 

<img width="1052" alt="image" src="https://github.com/colinwilson/lotusdocs/assets/17709352/88a1a4f6-21f4-4a6f-a90b-d5a732bab3a7">

### Expected behavior

Indent alerts when they are placed within an ordered list. 

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Browser Version: 116
```

**Comment by colinwilson** [comment]
Try using `{{<..>}}` pairs instead of `{{%..%}}`.

For example :
```
    {{< alert icon="🍅" context="success" >}}
    This is an alert that should be indented.
    {{< /alert >}}
```

**Comment by Nadine2016** [comment]
Hey Colin, 

thanks! That worked. We are using markdown within some alert so it would be more convenient to have the option to use `{{%..%}}`. But we can also use HTML tags as a workaround.

**Comment by colinwilson** [comment]
> We are using markdown within some alert

I'm currently testing [`.Renderstring`](https://gohugo.io/functions/renderstring/) with the alert shortcode. It should enable you to use markdown inside the `{{<..>}}` syntax.

**Edit**: I'll push this update very soon (24 hrs or so)

**Comment by colinwilson** [comment]
The `.RenderString` solution was not viable. Closing this for now. Will revisit at a later date.
