### ISSUE TITLE
Create an example repo to showcase the more advanced features of Lotus Docs

### ISSUE THREAD

**Issue by colinwilson** [colinwilson/lotusdocs#7]
The `exampleSite` folder provides a basic example of Lotus Docs. 

Create a separate repo (Starter Theme) to showcase features such as [DocSearch](https://docsearch.algolia.com/) integration and [Vercel](https://vercel.com/) deployment

**Comment by colinwilson** [comment]
Leverage the [lotusdocs.dev](https://lotusdocs.dev) site and repo with additional documentation instead of creating yet another repo.

**Comment by Synomega** [comment]
Hi, I tried to deploy https://github.com/colinwilson/lotusdocs.dev on vercel but there are errors : 

`
Error: Error building site: "/vercel/path0/content/docs/quickstart.md:33:1": failed to extract shortcode: template for shortcode "tabs" not found
Error: Command "hugo --gc" exited with 255
`
I set Hugo as a Framework preset, it is working on your side ?

Thanks
